services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres-container
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=postgres
    networks:
      - project-net
    volumes:
      - project-volume:/var/lib/postgresql/data
    hostname: postgresdb

  accessment:
    image:  machine-test:latest
    build: .
    restart: on-failure
    container_name: accessment-container
    depends_on:
      - postgres
    networks:
      - project-net
    ports:
      - "3000:3000"


volumes:
  project-volume:

networks:
  project-net:
    driver : bridge
